services:
    frontend-app:
        image: neurochar-frontend-cabinet:v1
        restart: unless-stopped
        ports:
            - 127.0.0.1:3020:3000
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "5" 
        environment:
            NUXT_PUBLIC_TENANT: ""
            NUXT_PUBLIC_API_BASE: https://api.neurochar.ru
            NUXT_PUBLIC_MAIN_URL: https://neurochar.ru
            NUXT_PUBLIC_ROOM_URL: https://room.neurochar.ru